repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: docker compose exec -T api pytest
        language: system
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: docker compose exec -T api mypy app/
        language: system
        types_or: [python, pyi]
        pass_filenames: false
      - id: ruff
        name: ruff
        entry: docker compose exec -T api ruff check
        language: system
        types_or: [python, pyi]
      - id: ruff-format
        name: ruff format
        entry: docker compose exec -T api ruff format
        language: system
        types_or: [python, pyi]