version: '3.8'

services:
  api:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    container_name: classifier_api
    ports:
      - "8000:8000"
 
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 
    volumes:
      - sqlite_data:/app/data
    depends_on:
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    env_file:
      - .env

  worker:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    command: python app/worker.py
    volumes:
      - sqlite_data:/app/data
      - ./Backend/models:/models
    depends_on:
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - OMP_NUM_THREADS=2
      - OPENBLAS_NUM_THREADS=2
      - MKL_NUM_THREADS=2
      - VECLIB_MAXIMUM_THREADS=2
      - NUMEXPR_NUM_THREADS=2

  redis:
    image: redis:7-alpine
    container_name: classifier_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 2s
      retries: 5
  locust:
    image: locustio/locust
    container_name: classifier_locust
    profiles: ["test"]  
    ports:
      - "8089:8089"
    volumes:
      - ./Backend/tests:/mnt/locust
    command: -f /mnt/locust/locustfile.py --host http://api:8000
    depends_on:
      - api
  minio:
    image: minio/minio:latest
    container_name: classifier_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 3s
      timeout: 2s
      retries: 10

volumes:
  sqlite_data:
  minio_data: