FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    wget \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

COPY pyproject.toml .


COPY app ./app
COPY templates ./templates
COPY tests ./tests

RUN uv pip install --system --no-cache -e ".[dev]"
ENV PYTHONPATH=/app/app

EXPOSE 8000